# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'
use_frameworks!

target 'DMSDriver' do

  # Pods for DMSDriver

  	pod 'GoogleMaps'	
	pod 'ObjectMapper'
	pod 'Alamofire'
	pod 'XLPagerTabStrip'
	pod 'IQKeyboardManager'
  	pod 'SVProgressHUD'
  	pod 'TLPhotoPicker'
 	pod 'SDWebImage'
  	pod 'Firebase/Core'
 	pod 'Firebase/Messaging'
    pod 'SideMenu', '~> 4.0.0'
    pod 'ReachabilitySwift', '~> 3'
    pod 'Socket.IO-Client-Swift', '~> 13.3.0'

end

