# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'
use_frameworks!

def shared_pods
    # Pods for DMSDriver
    pod 'GoogleMaps'
    pod 'ObjectMapper'
    pod 'Alamofire'
    pod 'XLPagerTabStrip'
    pod 'IQKeyboardManager'
    pod 'SVProgressHUD'
    pod 'TLPhotoPicker'
    pod 'SDWebImage'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'SideMenu', '~> 4.0.0'
    pod 'ReachabilitySwift', '~> 3'
    pod 'Socket.IO-Client-Swift', '~> 13.3.0'
    pod 'FDFullscreenPopGesture', '1.1'
    pod 'Charts'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'ImageSlideshow'
    pod 'UITextView+Placeholder'
    pod 'Floaty'
    pod 'DropDown'
end

target 'Gadot Dev' do
    shared_pods
end

target 'Gadot Live' do
    shared_pods
end

# Workaround for Cocoapods issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
