# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
 use_frameworks!
target 'DMSDriver' do

  # Pods for DMSDriver

  	pod 'GoogleMaps'	
	pod 'ObjectMapper'
	pod 'Alamofire'
	pod 'XLPagerTabStrip'
	pod 'IQKeyboardManager'
  	pod 'SVProgressHUD'
  	pod 'TLPhotoPicker'
 	pod 'SDWebImage'
  	pod 'Firebase/Core'
 	pod 'Firebase/Messaging'
    pod 'SideMenu'

end

# Workaround for Cocoapods issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
